pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t prathikm/marineni App2/'
                }
            }
        }

                stage('Run Docker Image') {
            steps {
                script {
                    sh 'docker run -p 5000:5000 prathikm/marineni'
                    }
                }
            }
        }
    }
            
